### ISSUE TITLE
Fall back to account name if official name not available

### ISSUE THREAD

**Issue by davestimpert** [kevinschaich/mintable#16]
I have an account who's official_name is `null`, so it would be nice if I could have it fall back to `name` if `official_name` is `null`.  This is tricky, though, because columns are configurable.

**Comment by kevinschaich** [comment]
Hey @davestimpert – I've been meaning to tackle this for a while but I needed to refactor a couple things first so that we maintain backwards compatibility.

After some thinking, I think it's better to implement this at the _provider_ level rather than the _global_ level. The Plaid provider should be smart enough to preference the most complete name so that Mintable doesn't need to know about the internals of what's returned by Plaid.

I think #28 / [the `v1.2.1` release](https://github.com/kevinschaich/mintable/releases/tag/1.2.1) should fix this for you. You'll want to run `yarn migrate` if you're still on an older version of Mintable, and then changing the following in `mintable.config.json` should do the trick:

```diff 
{
  ...
  "TRANSACTION_COLUMNS": [
    "date",
    "amount",
    "name",
-   "account_details.official_name",
+  "account"
    "category.0",
    "category.1",
    "pending"
  ],
  ...
}
```
