### ISSUE TITLE
Bug: v2.0.0 Beta - Clicking 'link a new account' is showing me the success screen of my last authentication

### ISSUE THREAD

**Issue by yawhide** [kevinschaich/mintable#70]
Hello,

In following the steps to migrate from v1 to v2, I had to update one of my bank accounts (got the error ` PlaidError: ITEM_LOGIN_REQUIRED` after running `mintable fetch`.
1. I ran `mintable account-setup`
2. clicked update on the outdated bank account
3. successfully completed the handshake with plaid. 
4. I then got back to the main screen (titled `Plaid – Account Configuration`) and clicked  `Link a new account`.
5. It then redirects me back to plaid and shows me the success screen on step 3.

seeing this in the terminal

```
2020-06-24T22:18:29.688Z [ERROR] Encountered error during authentication.

 {
  display_message: '',
  error_code: 'item-no-error',
  error_message: '',
  error_type: ''
}
```

I cannot link a new account.

6. i reran `mintable account-setup` and I see a duplicate row now for the bank account i updated in step 1-3. Pressing `link new account` now works correctly.

**Comment by kevinschaich** [comment]
Thanks @yawhide – I think this is fixed in #76. Refreshing after the Plaid auth result should do the trick.

Can you confirm whether this fixes the issue on `v2.0.0-beta.32`?

You should be able to upgrade versions by running:

```bash
npm install -g mintable
```

**Comment by yawhide** [comment]
cant really test this as I dont have an outdated account. but sounds like that would fix it.

**Comment by kevinschaich** [comment]
Sounds good @yawhide – let me know if it comes up again.

**Comment by yawhide** [comment]
one of my auth's expired so i can test this out again.

so updating the account work, the the page refreshed. BUT now i have 2 rows instead of 1 (both accounts look identical).
Looks like there is a bug here:
![Screen Shot 2020-07-01 at 8 39 31 AM](https://user-images.githubusercontent.com/5014112/86244980-c5f62780-bb76-11ea-874e-51ce4eaf92ef.png)

**Comment by kevinschaich** [comment]
Hey @yawhide, I think I know what happened here, does this sound right?

1. You linked your account in `v1.x.x` and gave it the name `SIMPLII`
1. You migrated your config to `v2.x.x`, and upon running `mintable account-setup` you were prompted to update your account
1. You re-authenticated for that account which updated the access token for the `SIMPLII` entry in your config
1. Page did not refresh (prior to the above bugfix), so Plaid Link was not correctly re-initialized in `create` mode (instead it got stuck in `update` mode for your `SIMPLII` account)
1. Clicking **Link New Account** showed the existing success screen since it was stuck in `update` mode, **but** in the `v2.0.0` link flow, we removed custom account names from Plaid so that the ID just gets set to the access token instead of `SIMPLII`
1. After actually reloading the page there were two accounts in your `~/mintable.jsonc` (and similarly showing on the Account Setup page)

If that sounds right, I think the bugfix above would have fixed **Step 4** above. If Plaid Link had been re-initialized in `create` mode it would not have essentially duplicated your account with a different ID, it would have prompted you to sign in with different credentials.

Here's what I think we should do:

1. Make a backup copy of your new `v2.x.x ~/mintable.jsonc`
1. Manually remove this block from your config:

    ```
    "SIMPLII": {
      "id": "SIMPLII",
      "integration": "plaid",
      "token": "...10eba22"
    },
    ```

I think that will resolve your duplicate issue, and I'm confident that if you were to go through this process again you wouldn't hit this (although I don't want to have you try it again since it will use up one of your Plaid dev tokens).

Let me know how that sounds! 😄

**Comment by yawhide** [comment]
1-6 sounds about right

I made a backup and removed the block from the config.
looks good!

**Comment by gbdavidx** [comment]
the link doesnt open on the latest version, how can i get a code?
