### ISSUE TITLE
Enhancement: change google sheet oauth2 scope to https://www.googleapis.com/auth/drive.file

### ISSUE THREAD

**Issue by yawhide** [kevinschaich/mintable#85]
Hello,

I was reading over the differences between these two scopes:

scope | description
-- | --
https://www.googleapis.com/auth/drive.file | View and manage Google Drive files and folders that you have opened or created with this app
https://www.googleapis.com/auth/spreadsheets | See, edit, create, and delete your spreadsheets in Google Drive

Disregarding migrating scripts over from v1 to v2, all new users of this project could use the `drive.file` scope instead (and it seems a bit safer as it would only have access to the spreadsheet created by this app).

what are your thoughts?

**Comment by kevinschaich** [comment]
Hey @yawhide – not opposed but before we spend time changing things I'd want to hear the community's thoughts on a few exploratory questions:

1. Mintable is not "creating" a spreadsheet, currently – that's currently a manual step by the user. How would one specify which spreadsheets are "authorized to be opened" during setup, given that none have been opened so far?
1. Would this break template sheets? i.e. your account needs to read from a view-only public sheet which is owned by my account?
3. Would this create more friction in changing your config? i.e. if you want to start using a new sheet and you change `documentId`, will it prompt you to reauthenticate / throw an error?

In general I'd like to steer away from extra `Do you authorize Mintable to use X spreadsheet?` prompts any time you edit your config, since it is unnecessary user experience bloat.

**Comment by yawhide** [comment]
1. I think how it would work is if there is no doc_id in the config, mintable would create one. If there is a doc_id in the config, you can assume you have access to it. (migrations would be tricky here). I dont think you would have to worry about knowing which spreadsheets are authorized to be opened. The downside is this would be a breaking change. 
2. I believe if a sheet is public, that has nothing to do with authorization. Keep the template sheet public and it'll keep working.
3. So the migration would be to not change the config and let mintable create the spreadsheet (no extra authorization) and let mintable write the new document id into the config. Again migration is the biggest pain here as the migration would require 2 tokens each with different scopes.


The biggest strength to this is that mintable doesnt need read/write access to all spreadsheets in your google drive. It only needs access to 1. 
Biggest downside is the migration is not clean and would probably require users to manually copy data over OR have mintable create a temporary access-token with the old scopes and use that to migrate. We would then have to self destruct the token.

**Comment by kevinschaich** [comment]
Hey @yawhide – this is now the default scope, thanks for your suggestion:

https://github.com/kevinschaich/mintable/blob/8b97b7c7e770edeb2bfaaec5285559f8089d7cb0/src/types/integrations/google.ts#L41
