### ISSUE TITLE
Enhancement: Allow csv-import to create new spreadsheet tabs

### ISSUE THREAD

**Issue by yawhide** [kevinschaich/mintable#88]
Mintable does not create a new tab when there are transactions in a csv-import that do not fall into any of the existing spreadsheet tabs.

eg. I have transactions from 04-2020  and 05-2020 but mintable only creates 2 tabs, 05-2020 and 06-2020 and does not create 04-2020.

Not sure if this is a bug or enhancement 😅

**Comment by kevinschaich** [comment]
Hey @yawhide – this is actually a feature. The imported CSV transactions get filtered in the same way as Plaid and other integrations. If you place your CSVs into one or a few big folders, you could potentially have history for several years. On the other hand, for some banks Plaid only provides history for the last ~6 months.

If we didn't do the filtering step, your CSVs would update since the beginning of time, clearing the respective sheets, but Plaid would only be able to keep up for the last few months, effectively deleting all Plaid older than 6 months.

If you want to do a one-time run to populate history for CSVs, just specify `transactions.startDate` and `transactions.endDate` in your config:

https://github.com/kevinschaich/mintable/blob/22b410fc038c728463fba07d120dc7b4af27a541/src/scripts/fetch.ts#L11-L19

I'd recommend making a backup copy of your sheet if it's more than a few months of history 🙂

**Comment by kevinschaich** [comment]
Hey @yawhide any luck getting your CSV history to populate?

**Comment by yawhide** [comment]
> Hey @yawhide any luck getting your CSV history to populate?

didnt try. i am not too concerned with being able to populate history in this case. was more of an observation

**Comment by kevinschaich** [comment]
Sounds good! Will close this out for now if the behavior here is not limiting functionality 👍
