### ISSUE TITLE
2.0 duplicates category columns and adds 'notes' 'work' 'joint' regardless of config

### ISSUE THREAD

**Issue by Nojwe** [kevinschaich/mintable#97]
I just migrated to the 2.0 beta and it's been great. I'm running into an issue with the column management. Here is the relevant portion of my JSONC:

`  "transactions": {
    "integration": "google",
    "properties": [
      "date",
      "amount",
      "name",
      "account",
      "category",
      "pending"
    ]`

However, the output on my Google Sheet includes the following: 

![image](https://user-images.githubusercontent.com/46374242/87444336-ab836b80-c5c4-11ea-9cfd-e3e891c1bfcd.png)

**Comment by kevinschaich** [comment]
Hey @Nojwe,

What beta version are you on? In my local repo (`v2.0.0-beta.45`) I did a search for `joint` and there are zero references, so it's definitely not coming from the code. If you're not on the latest version a good first step would be running `npm install mintable -g` to upgrade. Perhaps this was a bug with a previous version of the migration script.

From a behavior standpoint Mintable only clears data in columns which you have set as automated. In this case, you have 6 in your config, so only columns A-F are being cleared (as to not override any formulas you've set to the right). That's why notes, work, and joint are not getting cleared – it is curious though that category is appearing twice rather than pending.

A few questions:

- Are you positive that snippet from the config is the one that Mintable is actually using (default is `~/mintable.jsonc`)?
- Are you using a template sheet?
- Can you try manually deleting everything in row 1 and then run `mintable fetch` again?

**Comment by Nojwe** [comment]
Hi,

I'm on 2.0.0-beta.45. The snippet was from ~/mintable.jsonc. 

If I delete everything from the sheet and run `mintable fetch` it is now working correctly. However, if I delete the sheet and then run `mintable fetch` it now duplicates 'pending' and includes 'notes', 'work', and 'joint'. I assume it's pulling from a template somewhere or I really messed up the config somehow. 

![image](https://user-images.githubusercontent.com/46374242/87448368-bdb3d880-c5c9-11ea-9948-ac2fcf16d5fc.png)

**Comment by Nojwe** [comment]
Based on your comment in #98 I'll try a clean reinstall and see if that clears things up.

**Comment by Nojwe** [comment]
Everything seems to be working fine now after a clean install. Sorry for opening a needless issue!

**Comment by kevinschaich** [comment]
Not a problem thanks for raising an issue!
